/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.awd.api;

import io.swagger.client.awd.model.ErrorList;
import io.swagger.client.awd.model.InboundEligibility;
import io.swagger.client.awd.model.InboundOrder;
import io.swagger.client.awd.model.InboundOrderCreationData;
import io.swagger.client.awd.model.InboundOrderReference;
import io.swagger.client.awd.model.InboundPackages;
import io.swagger.client.awd.model.InboundShipment;
import io.swagger.client.awd.model.InventoryListing;
import org.threeten.bp.OffsetDateTime;
import io.swagger.client.awd.model.ShipmentLabels;
import io.swagger.client.awd.model.ShipmentListing;
import io.swagger.client.awd.model.TransportationDetails;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AwdApi
 */
@Ignore
public class AwdApiTest {

    private final AwdApi api = new AwdApi();

    
    /**
     * 
     *
     * Cancels an AWD Inbound order and its associated shipment.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void cancelInboundTest() throws Exception {
        String orderId = null;
        api.cancelInbound(orderId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Determines if the packages you specify are eligible for an AWD inbound order and contains error details for ineligible packages.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void checkInboundEligibilityTest() throws Exception {
        InboundPackages body = null;
        InboundEligibility response = api.checkInboundEligibility(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Confirms an AWD inbound order in &#x60;DRAFT&#x60; status.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void confirmInboundTest() throws Exception {
        String orderId = null;
        api.confirmInbound(orderId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Creates a draft AWD inbound order with a list of packages for inbound shipment. The operation creates one shipment per order.   **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createInboundTest() throws Exception {
        InboundOrderCreationData body = null;
        InboundOrderReference response = api.createInbound(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieves an AWD inbound order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 2 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInboundTest() throws Exception {
        String orderId = null;
        InboundOrder response = api.getInbound(orderId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieves an AWD inbound shipment.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 2 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api)
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInboundShipmentTest() throws Exception {
        String shipmentId = null;
        String skuQuantities = null;
        InboundShipment response = api.getInboundShipment(shipmentId, skuQuantities);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieves the box labels for a shipment ID that you specify. This is an asynchronous operation. If the label status is &#x60;GENERATED&#x60;, then the label URL is available.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 2 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInboundShipmentLabelsTest() throws Exception {
        String shipmentId = null;
        String pageType = null;
        String formatType = null;
        ShipmentLabels response = api.getInboundShipmentLabels(shipmentId, pageType, formatType);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieves a summary of all the inbound AWD shipments associated with a merchant, with the ability to apply optional filters.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listInboundShipmentsTest() throws Exception {
        String sortBy = null;
        String sortOrder = null;
        String shipmentStatus = null;
        OffsetDateTime updatedAfter = null;
        OffsetDateTime updatedBefore = null;
        Integer maxResults = null;
        String nextToken = null;
        ShipmentListing response = api.listInboundShipments(sortBy, sortOrder, shipmentStatus, updatedAfter, updatedBefore, maxResults, nextToken);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Lists AWD inventory associated with a merchant with the ability to apply optional filters.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 2 | 2 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listInventoryTest() throws Exception {
        String sku = null;
        String sortOrder = null;
        String details = null;
        String nextToken = null;
        Integer maxResults = null;
        InventoryListing response = api.listInventory(sku, sortOrder, details, nextToken, maxResults);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Updates an AWD inbound order that is in &#x60;DRAFT&#x60; status and not yet confirmed. Use this operation to update the &#x60;packagesToInbound&#x60;, &#x60;originAddress&#x60; and &#x60;preferences&#x60; attributes.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateInboundTest() throws Exception {
        String orderId = null;
        InboundOrder body = null;
        api.updateInbound(orderId, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Updates transport details for an AWD shipment.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 1 |  The &#x60;x-amzn-RateLimit-Limit&#x60; response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateInboundShipmentTransportDetailsTest() throws Exception {
        String shipmentId = null;
        TransportationDetails body = null;
        api.updateInboundShipmentTransportDetails(shipmentId, body);

        // TODO: test validations
    }
    
}
