/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.awd.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.awd.model.Address;
import io.swagger.client.awd.model.DestinationDetails;
import io.swagger.client.awd.model.DistributionPackageQuantity;
import io.swagger.client.awd.model.InboundPreferences;
import io.swagger.client.awd.model.InboundStatus;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents an AWD inbound order.
 */
@ApiModel(description = "Represents an AWD inbound order.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-25T16:01:36.172+08:00")
public class InboundOrder {
  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("destinationDetails")
  private DestinationDetails destinationDetails = null;

  @SerializedName("externalReferenceId")
  private String externalReferenceId = null;

  @SerializedName("orderId")
  private String orderId = null;

  @SerializedName("orderStatus")
  private InboundStatus orderStatus = null;

  @SerializedName("originAddress")
  private Address originAddress = null;

  @SerializedName("packagesToInbound")
  private List<DistributionPackageQuantity> packagesToInbound = new ArrayList<DistributionPackageQuantity>();

  @SerializedName("preferences")
  private InboundPreferences preferences = null;

  @SerializedName("updatedAt")
  private OffsetDateTime updatedAt = null;

  public InboundOrder createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Date when this order was created.
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "Date when this order was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public InboundOrder destinationDetails(DestinationDetails destinationDetails) {
    this.destinationDetails = destinationDetails;
    return this;
  }

   /**
   * Destination details of an inbound order based on the assigned region and DC for the order.
   * @return destinationDetails
  **/
  @ApiModelProperty(value = "Destination details of an inbound order based on the assigned region and DC for the order.")
  public DestinationDetails getDestinationDetails() {
    return destinationDetails;
  }

  public void setDestinationDetails(DestinationDetails destinationDetails) {
    this.destinationDetails = destinationDetails;
  }

  public InboundOrder externalReferenceId(String externalReferenceId) {
    this.externalReferenceId = externalReferenceId;
    return this;
  }

   /**
   * Reference ID that can be used to correlate the order with partner resources.
   * @return externalReferenceId
  **/
  @ApiModelProperty(example = "TestReferenceId", value = "Reference ID that can be used to correlate the order with partner resources.")
  public String getExternalReferenceId() {
    return externalReferenceId;
  }

  public void setExternalReferenceId(String externalReferenceId) {
    this.externalReferenceId = externalReferenceId;
  }

  public InboundOrder orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Inbound order ID.
   * @return orderId
  **/
  @ApiModelProperty(required = true, value = "Inbound order ID.")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public InboundOrder orderStatus(InboundStatus orderStatus) {
    this.orderStatus = orderStatus;
    return this;
  }

   /**
   * Inbound order status.
   * @return orderStatus
  **/
  @ApiModelProperty(required = true, value = "Inbound order status.")
  public InboundStatus getOrderStatus() {
    return orderStatus;
  }

  public void setOrderStatus(InboundStatus orderStatus) {
    this.orderStatus = orderStatus;
  }

  public InboundOrder originAddress(Address originAddress) {
    this.originAddress = originAddress;
    return this;
  }

   /**
   * Origin address from where the inbound order will be shipped.
   * @return originAddress
  **/
  @ApiModelProperty(required = true, value = "Origin address from where the inbound order will be shipped.")
  public Address getOriginAddress() {
    return originAddress;
  }

  public void setOriginAddress(Address originAddress) {
    this.originAddress = originAddress;
  }

  public InboundOrder packagesToInbound(List<DistributionPackageQuantity> packagesToInbound) {
    this.packagesToInbound = packagesToInbound;
    return this;
  }

  public InboundOrder addPackagesToInboundItem(DistributionPackageQuantity packagesToInboundItem) {
    this.packagesToInbound.add(packagesToInboundItem);
    return this;
  }

   /**
   * List of packages to be inbounded.
   * @return packagesToInbound
  **/
  @ApiModelProperty(required = true, value = "List of packages to be inbounded.")
  public List<DistributionPackageQuantity> getPackagesToInbound() {
    return packagesToInbound;
  }

  public void setPackagesToInbound(List<DistributionPackageQuantity> packagesToInbound) {
    this.packagesToInbound = packagesToInbound;
  }

  public InboundOrder preferences(InboundPreferences preferences) {
    this.preferences = preferences;
    return this;
  }

   /**
   * Get preferences
   * @return preferences
  **/
  @ApiModelProperty(value = "")
  public InboundPreferences getPreferences() {
    return preferences;
  }

  public void setPreferences(InboundPreferences preferences) {
    this.preferences = preferences;
  }

  public InboundOrder updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Date when this order was last updated.
   * @return updatedAt
  **/
  @ApiModelProperty(value = "Date when this order was last updated.")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundOrder inboundOrder = (InboundOrder) o;
    return Objects.equals(this.createdAt, inboundOrder.createdAt) &&
        Objects.equals(this.destinationDetails, inboundOrder.destinationDetails) &&
        Objects.equals(this.externalReferenceId, inboundOrder.externalReferenceId) &&
        Objects.equals(this.orderId, inboundOrder.orderId) &&
        Objects.equals(this.orderStatus, inboundOrder.orderStatus) &&
        Objects.equals(this.originAddress, inboundOrder.originAddress) &&
        Objects.equals(this.packagesToInbound, inboundOrder.packagesToInbound) &&
        Objects.equals(this.preferences, inboundOrder.preferences) &&
        Objects.equals(this.updatedAt, inboundOrder.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, destinationDetails, externalReferenceId, orderId, orderStatus, originAddress, packagesToInbound, preferences, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundOrder {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    destinationDetails: ").append(toIndentedString(destinationDetails)).append("\n");
    sb.append("    externalReferenceId: ").append(toIndentedString(externalReferenceId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderStatus: ").append(toIndentedString(orderStatus)).append("\n");
    sb.append("    originAddress: ").append(toIndentedString(originAddress)).append("\n");
    sb.append("    packagesToInbound: ").append(toIndentedString(packagesToInbound)).append("\n");
    sb.append("    preferences: ").append(toIndentedString(preferences)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

