/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.awd.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.awd.model.LabelStatus;
import java.io.IOException;

/**
 * Shipment labels.
 */
@ApiModel(description = "Shipment labels.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-25T16:01:36.172+08:00")
public class ShipmentLabels {
  @SerializedName("labelDownloadURL")
  private String labelDownloadURL = null;

  @SerializedName("labelStatus")
  private LabelStatus labelStatus = null;

  public ShipmentLabels labelDownloadURL(String labelDownloadURL) {
    this.labelDownloadURL = labelDownloadURL;
    return this;
  }

   /**
   * The URL to download shipment labels. The URL is active for 600 seconds from generation.
   * @return labelDownloadURL
  **/
  @ApiModelProperty(value = "The URL to download shipment labels. The URL is active for 600 seconds from generation.")
  public String getLabelDownloadURL() {
    return labelDownloadURL;
  }

  public void setLabelDownloadURL(String labelDownloadURL) {
    this.labelDownloadURL = labelDownloadURL;
  }

  public ShipmentLabels labelStatus(LabelStatus labelStatus) {
    this.labelStatus = labelStatus;
    return this;
  }

   /**
   * Status of label generation.
   * @return labelStatus
  **/
  @ApiModelProperty(required = true, value = "Status of label generation.")
  public LabelStatus getLabelStatus() {
    return labelStatus;
  }

  public void setLabelStatus(LabelStatus labelStatus) {
    this.labelStatus = labelStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShipmentLabels shipmentLabels = (ShipmentLabels) o;
    return Objects.equals(this.labelDownloadURL, shipmentLabels.labelDownloadURL) &&
        Objects.equals(this.labelStatus, shipmentLabels.labelStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelDownloadURL, labelStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShipmentLabels {\n");
    
    sb.append("    labelDownloadURL: ").append(toIndentedString(labelDownloadURL)).append("\n");
    sb.append("    labelStatus: ").append(toIndentedString(labelStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

