/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.awd.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.awd.model.TrackingDetails;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Transportation details for the shipment.
 */
@ApiModel(description = "Transportation details for the shipment.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-06-25T16:01:36.172+08:00")
public class TransportationDetails {
  @SerializedName("trackingDetails")
  private List<TrackingDetails> trackingDetails = new ArrayList<TrackingDetails>();

  public TransportationDetails trackingDetails(List<TrackingDetails> trackingDetails) {
    this.trackingDetails = trackingDetails;
    return this;
  }

  public TransportationDetails addTrackingDetailsItem(TrackingDetails trackingDetailsItem) {
    this.trackingDetails.add(trackingDetailsItem);
    return this;
  }

   /**
   * Tracking details for the shipment. If using SPD transportation, this can be for each case. If not using SPD transportation, this is a single tracking entry for the entire shipment.
   * @return trackingDetails
  **/
  @ApiModelProperty(required = true, value = "Tracking details for the shipment. If using SPD transportation, this can be for each case. If not using SPD transportation, this is a single tracking entry for the entire shipment.")
  public List<TrackingDetails> getTrackingDetails() {
    return trackingDetails;
  }

  public void setTrackingDetails(List<TrackingDetails> trackingDetails) {
    this.trackingDetails = trackingDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransportationDetails transportationDetails = (TransportationDetails) o;
    return Objects.equals(this.trackingDetails, transportationDetails.trackingDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackingDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransportationDetails {\n");
    
    sb.append("    trackingDetails: ").append(toIndentedString(trackingDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

